# Webserver container for WVU Lib Engine API
# Using Centos:latest base image
# Version 1

FROM trmccormick/centos6-mfcs
USER root

WORKDIR /home/mfcs.lib.wvu.edu

## Remove mysql server
RUN yum -y remove mysql-server

## Install mysql client and cron
RUN yum -y install mysql cronie

## Start cron
RUN service crond start

## check if cron is running
RUN chkconfig crond on

## Install required packages
RUN yum -y install ImageMagick php-pecl-imagick python-devel \
	perl-ExtUtils-CBuilder.x86_64 perl-ExtUtils-Embed.x86_64 \
    perl-ExtUtils-MakeMaker.x86_64 perl-ExtUtils-ParseXS.x86_64 \
    libjpeg-devel libpng-devel libtiff-devel SDL-devel agg-devel

## Install FFMPEG Dependencies
RUN yum -y install autoconf automake cmake freetype-devel gcc gcc-c++ \
    git libtool make mercurial nasm pkgconfig zlib-devel

## ClamAV
RUN yum -y install clamav clamav-db clamav-devel

ADD ./scripts/entrypoint.dev.sh /usr/bin/
RUN chmod -v +x /usr/bin/entrypoint.dev.sh

# Start the service
ENTRYPOINT ["/usr/bin/entrypoint.dev.sh"]
