FROM php:8.2-apache

WORKDIR /home/mfcs.lib.wvu.edu
ADD ./public_html /home/mfcs.lib.wvu.edu/public_html

# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential \   
    libldap2-dev \
    default-mysql-client \
    vim \
    git \
    cron \
    exactimage \
    imagemagick \
    ghostscript \
    libmagickwand-dev --no-install-recommends \
    && pecl install imagick    

# Install PHP extensions
RUN docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu/
RUN docker-php-ext-install mysqli pdo pdo_mysql ldap 
RUN docker-php-ext-enable imagick

# install composer
# RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Tesseract
# -------------------------------------------------------------------------------------------------
RUN apt-get install -y libleptonica-dev libtesseract-dev tesseract-ocr
# ------------------------------------------------------------------------------------------------- 

# FFMPEG Conversions
# -------------------------------------------------------------------------------------------------
RUN apt-get install -y cmake ffmpeg
# -------------------------------------------------------------------------------------------------

## ClamAV
# RUN apt-get -y install clamav clamav-db clamav-devel

# Update apache site for our custom location 
COPY ./config/000-default.conf /etc/apache2/sites-available/000-default.conf

EXPOSE 80

ADD ./scripts/entrypoint.dev.sh /usr/bin/entrypoint.dev.sh
RUN chmod -v +x /usr/bin/entrypoint.dev.sh

# Start the service
ENTRYPOINT ["bash", "/usr/bin/entrypoint.dev.sh"] 
