version: '2.1'
services:
  app:
    build: 
      context: ./
      dockerfile: Dockerfile.dev
    extra_hosts:
      - "database.lib.wvu.edu:172.17.0.1"
      - "www.libraries.wvu.edu:127.0.0.1"
    container_name: mfcs
    volumes:
      - .:/vagrant
      - ./data:/home/mfcs.lib.wvu.edu/data
      - ./scripts:/home/mfcs.lib.wvu.edu/scripts
      - ./SQLFiles:/home/mfcs.lib.wvu.edu/SQLFiles      
      - ./data/git_pull:/tmp/git
    env_file:
        - './env/.env.dev.mfcs' 
    ports:
      - "8080:80"
    depends_on:
      db:
          condition: service_healthy   
    healthcheck:
      test: curl --fail -s http://localhost:8080/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
  db:
    image: mysql:5.7.27
    container_name: db
    restart: on-failure
    ports:
      - "3306:3306"
    env_file:
      - './env/.env.dev.db'         
    volumes:
      - mysql:/var/lib/mysql
      - ./SQLFiles/setup-docker.sql:/docker-entrypoint-initdb.d/setup-docker.sql
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 30s
        retries: 10

volumes:
  mysql: