version: '2.1'
services:
  web:
    build: 
      context: ./
      dockerfile: Dockerfile.dev
    extra_hosts:
      - "database.lib.wvu.edu:172.17.0.1"
      - "www.libraries.wvu.edu:127.0.0.1"
    container_name: web
    volumes:
      - ./config:/config
      - ./config/config.ini:/home/mfcs.lib.wvu.edu/config.ini           
      - ./data/logs:/tmp/log
      - ./data/logs:/home/mfcs.lib.wvu.edu/serverConfiguration/serverLogs            
      - ./data/mfcs-data:/home/mfcs.lib.wvu.edu/data     
      - ./public_html:/home/mfcs.lib.wvu.edu/public_html
      - ./template:/home/mfcs.lib.wvu.edu/template
      - ./serverConfiguration:/home/mfcs.lib.wvu.edu/serverConfiguration    
      - ./SQLFiles:/home/mfcs.lib.wvu.edu/SQLFiles      
      - ./data/git:/tmp/git
      - ./mfcs-manual-imports:/home/mfcs.lib.wvu.edu/mfcs-manual-imports      
    env_file:
        - './env/.env.dev.mfcs' 
    ports:
      - "8080:80"
    depends_on:
      db:
          condition: service_healthy   
    healthcheck:
      test: curl --fail -s http://localhost:8080/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3     
  db:
    image: mysql:5.7.27
    container_name: db
    restart: on-failure
    ports:
      - "3306:3306"
    ulimits:
        nofile: # Fix memory leak issue on some systems when LimitCORE=infinity (containerd)
          soft: 1048576
          hard: 1048576      
    env_file:
      - './env/.env.dev.db'         
    volumes:
      - ./config/mysql.cnf:/etc/mysql/conf.d/mysql.cnf    
      - mysql:/var/lib/mysql
      - ./SQLFiles/setup-docker.sql:/docker-entrypoint-initdb.d/setup-docker.sql
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 30s
        retries: 10

volumes:
  mysql: