CREATE TABLE  `mfcs`.`fileProcessQueue` (
	`ID` INT( 10 ) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
	`formID` INT( 10 ) UNSIGNED NULL ,
	`pid` INT( 10 ) UNSIGNED NULL ,
	UNIQUE (`formID`)
) ENGINE = INNODB;
